package codegen

import "time"

// MakeHeader returns a standard generated-file header comment.
func MakeHeader() string {
    return "// Generated by Clockwise transpiler - do not edit\n// Generated: " + time.Now().UTC().Format(time.RFC3339) + "\n\n"
}
